spring.application.name=mcp2-secure-server
server.port=${PORT:8090}
server.shutdown=immediate
spring.threads.virtual.enabled=true

spring.ai.mcp.server.protocol=stateless
spring.ai.mcp.server.name=mcp2-secure-server
spring.ai.mcp.server.version=1.0.0

# The Authorization Server. It supports CIMD (client_id_metadata_document_supported=true)
mcp.auth.issuer-uri=${ISSUER_URI:https://login.jamesward.dev}
